export const TOGGLE_RESULTS = 'TOGGLE_RESULTS';
export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS';
export const PLAY_SONG = 'PLAY_SONG';
export const TOGGLE_PLAY_PAUSE = 'TOGGLE_PLAY_PAUSE';
export const RECEIVE_STREAM_URL = 'RECEIVE_STREAM_URL';
